from typing import Protocol, Callable, Awaitable, Any


class Subscription(Protocol):
    async def close(self) -> None: ...


class Transport(Protocol):
    async def publish(self, topic: str, signal: dict) -> None: ...
    async def subscribe(self, topic: str,
                        cb: Callable[[dict], Any | Awaitable[Any]]) -> Subscription: ...
    async def close(self) -> None: ...
