from typing import Protocol


def self_filter(agent_id: str, box: str | None, col: str,
                agent_ph: str, box_ph: str, box_view: bool = False) -> tuple[str, list]:
    """Build the predicate for messages the caller must NOT receive, plus extra
    positional args (empty here; reserved for the Postgres adapter in Plan 4).

    Default (box_view=False): exclude ONLY the exact-self identity, so any two
    distinct identities hear each other — including the bare-box root ('<box>') and
    a same-box session ('<box>-*'). This is the invariant for interactive
    conversation. It deliberately diverges from orchestra's board._self_filter,
    which also made the bare-box root deaf to its own sessions and caused a live bug.

    box_view=True is the Layer-1 catch-all DELIVERY mode (used later by the Stop-hook,
    which polls as the bare box): additionally suppress the box's own '<box>-*'
    sessions so the catch-all never re-injects session chatter. Only the delivery
    poll opts in; interactive poll/peek/list never do.

    `col` is the from-column; `agent_ph`/`box_ph` are the dialect placeholders (for
    sqlite use ':agent'/':box' named params so the reused agent placeholder is legal)."""
    if box_view and box and agent_id == box:
        return f"{col}<>{agent_ph} AND {col} NOT LIKE {agent_ph} || '-%'", []
    return f"{col}<>{agent_ph}", []


class Store(Protocol):
    async def create_room(self, name: str, creator: str, title: str | None = None) -> dict: ...
    async def get_room(self, name: str) -> dict | None: ...
    async def join(self, name: str, agent_id: str) -> dict: ...
    async def leave(self, name: str, agent_id: str) -> dict: ...
    async def say(self, name: str, agent_id: str, body: str, kind: str = "say") -> dict: ...
    async def is_member(self, name: str, agent_id: str) -> bool: ...
    async def members(self, name: str) -> list[str]: ...
    async def poll(self, agent_id: str, room: str | None = None, box: str | None = None,
                   box_view: bool = False) -> list[dict]: ...
    async def peek(self, agent_id: str, room: str | None = None, box: str | None = None,
                   box_view: bool = False) -> list[dict]: ...
    async def list_rooms(self, agent_id: str, box: str | None = None) -> list[dict]: ...
    async def all_rooms(self) -> list[dict]: ...
    async def box_rooms(self, box: str) -> list[str]: ...
    async def next_agent_seq(self, box: str, slug: str) -> int: ...
    async def mint_agent_token(self, box: str, label: str | None = None) -> str: ...
    async def box_for_token(self, token: str) -> str | None: ...
    async def box_has_token(self, box: str) -> bool: ...
    async def close(self) -> None: ...
